// <auto-generated />
namespace ICanHelp.Model.Migrations._2014._04
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class EmailUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201404241908133_EmailUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
